#!/bin/bash

################################################################################
# README Status Checker
#
# Purpose: Check status of README.md files across all portfolio projects
# Author: Generated by Git Operations Coordinator
# Date: 2025-10-18
#
# Usage: ./check_readme_status.sh
################################################################################

set -u  # Exit on undefined variable

# Configuration
BASE_DIR="/mnt/c/Users/brand/Development/Project_Workspace/active-development"

# Colors
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# Counters
TOTAL_PROJECTS=0
HAS_CHANGES=0
NO_CHANGES=0
NO_README=0
NOT_GIT_REPO=0

# Project list
PROJECTS=(
    "aves"
    "describe_it"
    "hablas"
    "language_learning_subjunctive_practice"
    "california_puzzle_game"
    "colombia_puzzle_game"
    "corporate_intel"
    "open_learn"
    "brandonjplambert"
    "online_language_learning_resources"
    "letratos"
    "fancy_monkey"
    "video_gen"
    "report_assistant"
    "internet"
    "agentic_learning"
    "algorithms_and_data_structures"
    "antagonism_assays"
    "close_reading"
    "deployment_sprint"
    "learning_voice_agent"
    "ai_stack_analysis"
    "sinonimos"
    "sinonimos_de_caminar"
    "sinonimos_de_hablar"
    "sinonimos_de_ver"
    "thematic_outline_gen"
)

print_colored() {
    local color=$1
    shift
    echo -e "${color}$@${NC}"
}

print_header() {
    print_colored "${CYAN}" "\n################################################################################"
    print_colored "${CYAN}" "# $1"
    print_colored "${CYAN}" "################################################################################"
}

check_project_status() {
    local project_name=$1
    local project_path="${BASE_DIR}/${project_name}"

    TOTAL_PROJECTS=$((TOTAL_PROJECTS + 1))

    # Check if directory exists
    if [ ! -d "${project_path}" ]; then
        print_colored "${YELLOW}" "⚠ ${project_name}: Directory not found"
        return
    fi

    # Check if git repo
    if [ ! -d "${project_path}/.git" ]; then
        print_colored "${YELLOW}" "⚠ ${project_name}: Not a git repository"
        NOT_GIT_REPO=$((NOT_GIT_REPO + 1))
        return
    fi

    # Check if README exists
    if [ ! -f "${project_path}/README.md" ]; then
        print_colored "${RED}" "✗ ${project_name}: No README.md found"
        NO_README=$((NO_README + 1))
        return
    fi

    # Check for changes
    cd "${project_path}"
    if git status --porcelain README.md 2>/dev/null | grep -q "README.md"; then
        local status=$(git status --porcelain README.md | awk '{print $1}')
        local status_text=""

        case ${status} in
            "M")
                status_text="Modified"
                ;;
            "A")
                status_text="Added"
                ;;
            "??")
                status_text="Untracked"
                ;;
            *)
                status_text="Changed (${status})"
                ;;
        esac

        print_colored "${GREEN}" "✓ ${project_name}: Has changes [${status_text}]"
        HAS_CHANGES=$((HAS_CHANGES + 1))

        # Show brief diff stats
        if [ "${status}" != "??" ]; then
            local diff_stats=$(git diff --stat README.md 2>/dev/null | tail -1)
            if [ -n "${diff_stats}" ]; then
                print_colored "${BLUE}" "  └─ ${diff_stats}"
            fi
        fi
    else
        print_colored "${BLUE}" "ℹ ${project_name}: No changes"
        NO_CHANGES=$((NO_CHANGES + 1))
    fi
}

generate_summary() {
    print_header "Summary"

    echo ""
    print_colored "${CYAN}" "Total Projects Checked:    ${TOTAL_PROJECTS}"
    print_colored "${GREEN}" "Projects with Changes:     ${HAS_CHANGES}"
    print_colored "${BLUE}" "Projects without Changes:  ${NO_CHANGES}"
    print_colored "${RED}" "Projects without README:   ${NO_README}"
    print_colored "${YELLOW}" "Not Git Repositories:      ${NOT_GIT_REPO}"
    echo ""

    if [ ${HAS_CHANGES} -gt 0 ]; then
        print_colored "${GREEN}" "Ready to commit ${HAS_CHANGES} README updates!"
        echo ""
        print_colored "${CYAN}" "Next steps:"
        print_colored "${BLUE}" "  1. Review changes: git diff README.md (in each project)"
        print_colored "${BLUE}" "  2. Dry run: ./commit_readme_updates.sh --dry-run"
        print_colored "${BLUE}" "  3. Commit: ./commit_readme_updates.sh --force"
    else
        print_colored "${YELLOW}" "No README changes detected across projects."
    fi
}

main() {
    print_header "README Status Check"
    print_colored "${BLUE}" "Checking ${#PROJECTS[@]} projects...\n"

    for project in "${PROJECTS[@]}"; do
        check_project_status "${project}"
    done

    generate_summary
}

main
