#!/bin/bash

################################################################################
# README Update Commit Script
#
# Purpose: Commit and push README.md updates across all portfolio projects
# Author: Generated by Git Operations Coordinator
# Date: 2025-10-18
#
# Usage:
#   ./commit_readme_updates.sh [--dry-run] [--force] [--specific PROJECT_NAME]
#
# Options:
#   --dry-run    : Show what would be done without executing
#   --force      : Skip confirmation prompts
#   --specific   : Only process specified project
################################################################################

set -e  # Exit on error
set -u  # Exit on undefined variable

# Configuration
BASE_DIR="/mnt/c/Users/brand/Development/Project_Workspace/active-development"
LOG_DIR="${BASE_DIR}/report_assistant/logs"
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
LOG_FILE="${LOG_DIR}/readme_commits_${TIMESTAMP}.log"
SUMMARY_FILE="${LOG_DIR}/readme_commits_summary_${TIMESTAMP}.txt"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Flags
DRY_RUN=false
FORCE=false
SPECIFIC_PROJECT=""

# Counters
TOTAL_PROJECTS=0
SUCCESSFUL_COMMITS=0
SKIPPED_PROJECTS=0
FAILED_COMMITS=0

# Project list - All 26+ projects from portfolio
PROJECTS=(
    # Language Learning (4 projects)
    "aves"
    "describe_it"
    "hablas"
    "language_learning_subjunctive_practice"

    # Puzzles (2 projects)
    "california_puzzle_game"
    "colombia_puzzle_game"

    # Open Source Research (2 projects)
    "corporate_intel"
    "open_learn"

    # Galleries & Portfolios (3 projects)
    "brandonjplambert"
    "online_language_learning_resources"
    "letratos"

    # E-commerce (1 project)
    "fancy_monkey"

    # Utilities (2 projects)
    "video_gen"
    "report_assistant"

    # Visualizations (1 project)
    "internet"

    # Additional Projects (11+ projects)
    "agentic_learning"
    "algorithms_and_data_structures"
    "antagonism_assays"
    "close_reading"
    "deployment_sprint"
    "learning_voice_agent"
    "ai_stack_analysis"
    "sinonimos"
    "sinonimos_de_caminar"
    "sinonimos_de_hablar"
    "sinonimos_de_ver"
    "thematic_outline_gen"
)

################################################################################
# Helper Functions
################################################################################

log() {
    local level=$1
    shift
    local message="$@"
    local timestamp=$(date +"%Y-%m-%d %H:%M:%S")
    echo "[${timestamp}] [${level}] ${message}" | tee -a "${LOG_FILE}"
}

print_colored() {
    local color=$1
    shift
    local message="$@"
    echo -e "${color}${message}${NC}"
}

print_header() {
    local message="$1"
    print_colored "${CYAN}" "
################################################################################
# ${message}
################################################################################"
}

print_success() {
    print_colored "${GREEN}" "✓ $@"
    log "SUCCESS" "$@"
}

print_error() {
    print_colored "${RED}" "✗ $@"
    log "ERROR" "$@"
}

print_warning() {
    print_colored "${YELLOW}" "⚠ $@"
    log "WARNING" "$@"
}

print_info() {
    print_colored "${BLUE}" "ℹ $@"
    log "INFO" "$@"
}

################################################################################
# Git Operations
################################################################################

check_git_repo() {
    local project_path=$1
    if [ ! -d "${project_path}/.git" ]; then
        return 1
    fi
    return 0
}

check_readme_exists() {
    local project_path=$1
    if [ ! -f "${project_path}/README.md" ]; then
        return 1
    fi
    return 0
}

check_readme_changes() {
    local project_path=$1
    cd "${project_path}"

    # Check if README.md has changes (modified or untracked)
    if git status --porcelain README.md 2>/dev/null | grep -q "README.md"; then
        return 0  # Has changes
    fi
    return 1  # No changes
}

check_remote_exists() {
    local project_path=$1
    cd "${project_path}"

    if git remote | grep -q "origin"; then
        return 0
    fi
    return 1
}

get_current_branch() {
    local project_path=$1
    cd "${project_path}"
    git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "master"
}

commit_and_push_readme() {
    local project_name=$1
    local project_path=$2

    print_info "Processing: ${project_name}"

    # Navigate to project
    cd "${project_path}" || {
        print_error "Cannot access project directory: ${project_path}"
        return 1
    }

    # Verify git repo
    if ! check_git_repo "${project_path}"; then
        print_warning "Not a git repository: ${project_name}"
        return 2
    fi

    # Verify README exists
    if ! check_readme_exists "${project_path}"; then
        print_warning "No README.md found: ${project_name}"
        return 2
    fi

    # Check for changes
    if ! check_readme_changes "${project_path}"; then
        print_info "No changes to README.md: ${project_name}"
        return 2
    fi

    # Check for remote
    if ! check_remote_exists "${project_path}"; then
        print_warning "No remote repository configured: ${project_name}"
        return 2
    fi

    # Get current branch
    local branch=$(get_current_branch "${project_path}")
    print_info "Current branch: ${branch}"

    if [ "${DRY_RUN}" = true ]; then
        print_info "[DRY RUN] Would commit and push README.md for ${project_name}"
        return 0
    fi

    # Stage README.md
    print_info "Staging README.md..."
    if ! git add README.md; then
        print_error "Failed to stage README.md: ${project_name}"
        return 1
    fi

    # Commit with standard message
    print_info "Creating commit..."
    local commit_message="docs: Update README with comprehensive project documentation

- Add detailed project overview and features
- Include installation and usage instructions
- Document tech stack and dependencies
- Add development workflow and contribution guidelines
- Include performance metrics and achievements

Generated as part of portfolio documentation update."

    if ! git commit -m "${commit_message}"; then
        print_error "Failed to commit README.md: ${project_name}"
        return 1
    fi

    # Push to remote
    print_info "Pushing to remote..."
    if ! git push origin "${branch}"; then
        print_error "Failed to push to remote: ${project_name}"
        print_warning "Commit created locally but not pushed"
        return 1
    fi

    print_success "Successfully committed and pushed README.md for ${project_name}"
    return 0
}

################################################################################
# Main Processing
################################################################################

process_project() {
    local project_name=$1
    local project_path="${BASE_DIR}/${project_name}"

    TOTAL_PROJECTS=$((TOTAL_PROJECTS + 1))

    echo ""
    print_header "Project ${TOTAL_PROJECTS}: ${project_name}"

    if [ ! -d "${project_path}" ]; then
        print_warning "Project directory not found: ${project_path}"
        SKIPPED_PROJECTS=$((SKIPPED_PROJECTS + 1))
        return
    fi

    commit_and_push_readme "${project_name}" "${project_path}"
    local result=$?

    case ${result} in
        0)
            SUCCESSFUL_COMMITS=$((SUCCESSFUL_COMMITS + 1))
            ;;
        1)
            FAILED_COMMITS=$((FAILED_COMMITS + 1))
            ;;
        2)
            SKIPPED_PROJECTS=$((SKIPPED_PROJECTS + 1))
            ;;
    esac
}

################################################################################
# Summary Report
################################################################################

generate_summary() {
    local summary="
################################################################################
# README Commit Summary Report
################################################################################

Generated: $(date)

## Overall Statistics

Total Projects Processed:  ${TOTAL_PROJECTS}
Successful Commits:        ${SUCCESSFUL_COMMITS}
Skipped Projects:          ${SKIPPED_PROJECTS}
Failed Commits:            ${FAILED_COMMITS}

## Success Rate

$(awk "BEGIN {printf \"%.2f%%\", (${SUCCESSFUL_COMMITS}/${TOTAL_PROJECTS})*100}")

## Detailed Log

Full log available at: ${LOG_FILE}

## Next Steps

1. Review failed commits (if any) and resolve issues
2. Verify remote repositories reflect README updates
3. Check GitHub/GitLab for proper rendering
4. Update portfolio documentation if needed

################################################################################
"

    echo "${summary}" | tee "${SUMMARY_FILE}"
    print_success "Summary report saved to: ${SUMMARY_FILE}"
}

################################################################################
# Argument Parsing
################################################################################

parse_arguments() {
    while [[ $# -gt 0 ]]; do
        case $1 in
            --dry-run)
                DRY_RUN=true
                print_info "DRY RUN MODE: No actual commits will be made"
                shift
                ;;
            --force)
                FORCE=true
                print_info "FORCE MODE: Skipping confirmations"
                shift
                ;;
            --specific)
                SPECIFIC_PROJECT="$2"
                print_info "SPECIFIC PROJECT MODE: Only processing ${SPECIFIC_PROJECT}"
                shift 2
                ;;
            -h|--help)
                print_info "Usage: $0 [--dry-run] [--force] [--specific PROJECT_NAME]"
                exit 0
                ;;
            *)
                print_error "Unknown option: $1"
                exit 1
                ;;
        esac
    done
}

################################################################################
# Initialization
################################################################################

initialize() {
    print_header "README Update Commit Script"

    # Create log directory if it doesn't exist
    mkdir -p "${LOG_DIR}"

    # Initialize log file
    log "INFO" "Script started"
    log "INFO" "Base directory: ${BASE_DIR}"
    log "INFO" "Log file: ${LOG_FILE}"

    print_info "Log file: ${LOG_FILE}"
}

################################################################################
# Confirmation
################################################################################

confirm_execution() {
    if [ "${FORCE}" = true ] || [ "${DRY_RUN}" = true ]; then
        return 0
    fi

    echo ""
    print_warning "This script will commit and push README.md changes for ${#PROJECTS[@]} projects."
    print_warning "This operation cannot be easily undone."
    echo ""
    read -p "Are you sure you want to continue? (yes/no): " confirmation

    if [ "${confirmation}" != "yes" ]; then
        print_info "Operation cancelled by user"
        exit 0
    fi
}

################################################################################
# Main Execution
################################################################################

main() {
    parse_arguments "$@"
    initialize
    confirm_execution

    print_header "Processing Projects"

    if [ -n "${SPECIFIC_PROJECT}" ]; then
        process_project "${SPECIFIC_PROJECT}"
    else
        for project in "${PROJECTS[@]}"; do
            process_project "${project}"
        done
    fi

    print_header "Execution Complete"
    generate_summary

    echo ""
    print_success "All operations completed!"
    print_info "Review the summary above and check the log file for details"
}

# Run main function with all arguments
main "$@"
